
package com.roboxchange.merchant.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-04T10:13:39.339+04:00
 * Generated source version: 3.0.4
 * 
 */
public final class ServiceSoap_ServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://merchant.roboxchange.com/WebService/", "Service");

    private ServiceSoap_ServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap12();  
        
        {
        System.out.println("Invoking getPaymentMethods...");
        java.lang.String _getPaymentMethods_merchantLogin = "";
        java.lang.String _getPaymentMethods_language = "";
        com.roboxchange.merchant.webservice.PaymentMethodsList _getPaymentMethods__return = port.getPaymentMethods(_getPaymentMethods_merchantLogin, _getPaymentMethods_language);
        System.out.println("getPaymentMethods.result=" + _getPaymentMethods__return);


        }
        {
        System.out.println("Invoking getLimit...");
        java.lang.String _getLimit_merchantLogin = "";
        com.roboxchange.merchant.webservice.LimitResponse _getLimit__return = port.getLimit(_getLimit_merchantLogin);
        System.out.println("getLimit.result=" + _getLimit__return);


        }
        {
        System.out.println("Invoking calcOutSumm...");
        java.lang.String _calcOutSumm_merchantLogin = "";
        java.lang.String _calcOutSumm_incCurrLabel = "";
        java.lang.String _calcOutSumm_incSum = "";
        com.roboxchange.merchant.webservice.CalcSummsResponseData _calcOutSumm__return = port.calcOutSumm(_calcOutSumm_merchantLogin, _calcOutSumm_incCurrLabel, _calcOutSumm_incSum);
        System.out.println("calcOutSumm.result=" + _calcOutSumm__return);


        }
        {
        System.out.println("Invoking getCurrencies...");
        java.lang.String _getCurrencies_merchantLogin = "";
        java.lang.String _getCurrencies_language = "";
        com.roboxchange.merchant.webservice.CurrenciesList _getCurrencies__return = port.getCurrencies(_getCurrencies_merchantLogin, _getCurrencies_language);
        System.out.println("getCurrencies.result=" + _getCurrencies__return);


        }
        {
        System.out.println("Invoking opState...");
        java.lang.String _opState_merchantLogin = "";
        int _opState_invoiceID = 0;
        java.lang.String _opState_signature = "";
        com.roboxchange.merchant.webservice.OperationStateResponse _opState__return = port.opState(_opState_merchantLogin, _opState_invoiceID, _opState_signature);
        System.out.println("opState.result=" + _opState__return);


        }
        {
        System.out.println("Invoking opStateExt...");
        java.lang.String _opStateExt_merchantLogin = "";
        int _opStateExt_invoiceID = 0;
        java.lang.String _opStateExt_signature = "";
        com.roboxchange.merchant.webservice.OperationStateResponse _opStateExt__return = port.opStateExt(_opStateExt_merchantLogin, _opStateExt_invoiceID, _opStateExt_signature);
        System.out.println("opStateExt.result=" + _opStateExt__return);


        }
        {
        System.out.println("Invoking getRates...");
        java.lang.String _getRates_merchantLogin = "";
        java.lang.String _getRates_incCurrLabel = "";
        java.lang.String _getRates_outSum = "";
        java.lang.String _getRates_language = "";
        com.roboxchange.merchant.webservice.RatesList _getRates__return = port.getRates(_getRates_merchantLogin, _getRates_incCurrLabel, _getRates_outSum, _getRates_language);
        System.out.println("getRates.result=" + _getRates__return);


        }

        System.exit(0);
    }

}
