package com.roboxchange.merchant.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-04T10:13:39.404+04:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://merchant.roboxchange.com/WebService/", name = "ServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceHttpPost {

    /**
     * Получение списка способов оплаты, доступных магазину
     */
    @WebResult(name = "PaymentMethodsList", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "GetPaymentMethods")
    public PaymentMethodsList getPaymentMethods(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "Language", name = "Language", targetNamespace = "")
        java.lang.String language
    );

    /**
     * Получение информации о доступном лимите платежей
     */
    @WebResult(name = "LimitResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "GetLimit")
    public LimitResponse getLimit(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin
    );

    /**
     * Расчет сумм оплаты в различных валютах
     */
    @WebResult(name = "CalcSummsResponseData", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "CalcOutSumm")
    public CalcSummsResponseData calcOutSumm(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "IncCurrLabel", name = "IncCurrLabel", targetNamespace = "")
        java.lang.String incCurrLabel,
        @WebParam(partName = "IncSum", name = "IncSum", targetNamespace = "")
        java.lang.String incSum
    );

    /**
     * Получение списка валют, доступных магазину
     */
    @WebResult(name = "CurrenciesList", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "GetCurrencies")
    public CurrenciesList getCurrencies(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "Language", name = "Language", targetNamespace = "")
        java.lang.String language
    );

    /**
     * Получение информации об операции и ее текущего состояния
     */
    @WebResult(name = "OperationStateResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "OpState")
    public OperationStateResponse opState(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "InvoiceID", name = "InvoiceID", targetNamespace = "")
        java.lang.String invoiceID,
        @WebParam(partName = "Signature", name = "Signature", targetNamespace = "")
        java.lang.String signature
    );

    /**
     * Получение информации об операции и ее текущего состояния
     */
    @WebResult(name = "OperationStateResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "OpStateExt")
    public OperationStateResponse opStateExt(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "InvoiceID", name = "InvoiceID", targetNamespace = "")
        java.lang.String invoiceID,
        @WebParam(partName = "Signature", name = "Signature", targetNamespace = "")
        java.lang.String signature
    );

    /**
     * Получение текущих курсов валют / расчет сумм оплаты в различных валютах
     */
    @WebResult(name = "RatesList", targetNamespace = "http://merchant.roboxchange.com/WebService/", partName = "Body")
    @WebMethod(operationName = "GetRates")
    public RatesList getRates(
        @WebParam(partName = "MerchantLogin", name = "MerchantLogin", targetNamespace = "")
        java.lang.String merchantLogin,
        @WebParam(partName = "IncCurrLabel", name = "IncCurrLabel", targetNamespace = "")
        java.lang.String incCurrLabel,
        @WebParam(partName = "OutSum", name = "OutSum", targetNamespace = "")
        java.lang.String outSum,
        @WebParam(partName = "Language", name = "Language", targetNamespace = "")
        java.lang.String language
    );
}
