package com.roboxchange.merchant.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-04T10:13:39.392+04:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://merchant.roboxchange.com/WebService/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * Получение списка способов оплаты, доступных магазину
     */
    @WebResult(name = "GetPaymentMethodsResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "GetPaymentMethods", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetPaymentMethods")
    @WebMethod(operationName = "GetPaymentMethods", action = "http://merchant.roboxchange.com/WebService/GetPaymentMethods")
    @ResponseWrapper(localName = "GetPaymentMethodsResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetPaymentMethodsResponse")
    public com.roboxchange.merchant.webservice.PaymentMethodsList getPaymentMethods(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "Language", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String language
    );

    /**
     * Получение информации о доступном лимите платежей
     */
    @WebResult(name = "GetLimitResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "GetLimit", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetLimit")
    @WebMethod(operationName = "GetLimit", action = "http://merchant.roboxchange.com/WebService/GetLimit")
    @ResponseWrapper(localName = "GetLimitResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetLimitResponse")
    public com.roboxchange.merchant.webservice.LimitResponse getLimit(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin
    );

    /**
     * Расчет сумм оплаты в различных валютах
     */
    @WebResult(name = "CalcOutSummResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "CalcOutSumm", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.CalcOutSumm")
    @WebMethod(operationName = "CalcOutSumm", action = "http://merchant.roboxchange.com/WebService/CalcOutSumm")
    @ResponseWrapper(localName = "CalcOutSummResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.CalcOutSummResponse")
    public com.roboxchange.merchant.webservice.CalcSummsResponseData calcOutSumm(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "IncCurrLabel", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String incCurrLabel,
        @WebParam(name = "IncSum", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String incSum
    );

    /**
     * Получение списка валют, доступных магазину
     */
    @WebResult(name = "GetCurrenciesResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "GetCurrencies", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetCurrencies")
    @WebMethod(operationName = "GetCurrencies", action = "http://merchant.roboxchange.com/WebService/GetCurrencies")
    @ResponseWrapper(localName = "GetCurrenciesResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetCurrenciesResponse")
    public com.roboxchange.merchant.webservice.CurrenciesList getCurrencies(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "Language", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String language
    );

    /**
     * Получение информации об операции и ее текущего состояния
     */
    @WebResult(name = "OpStateResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "OpState", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.OpState")
    @WebMethod(operationName = "OpState", action = "http://merchant.roboxchange.com/WebService/OpState")
    @ResponseWrapper(localName = "OpStateResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.OpStateResponse")
    public com.roboxchange.merchant.webservice.OperationStateResponse opState(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "InvoiceID", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        int invoiceID,
        @WebParam(name = "Signature", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String signature
    );

    /**
     * Получение информации об операции и ее текущего состояния
     */
    @WebResult(name = "OpStateExtResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "OpStateExt", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.OpStateExt")
    @WebMethod(operationName = "OpStateExt", action = "http://merchant.roboxchange.com/WebService/OpStateExt")
    @ResponseWrapper(localName = "OpStateExtResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.OpStateExtResponse")
    public com.roboxchange.merchant.webservice.OperationStateResponse opStateExt(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "InvoiceID", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        int invoiceID,
        @WebParam(name = "Signature", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String signature
    );

    /**
     * Получение текущих курсов валют / расчет сумм оплаты в различных валютах
     */
    @WebResult(name = "GetRatesResult", targetNamespace = "http://merchant.roboxchange.com/WebService/")
    @RequestWrapper(localName = "GetRates", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetRates")
    @WebMethod(operationName = "GetRates", action = "http://merchant.roboxchange.com/WebService/GetRates")
    @ResponseWrapper(localName = "GetRatesResponse", targetNamespace = "http://merchant.roboxchange.com/WebService/", className = "com.roboxchange.merchant.webservice.GetRatesResponse")
    public com.roboxchange.merchant.webservice.RatesList getRates(
        @WebParam(name = "MerchantLogin", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String merchantLogin,
        @WebParam(name = "IncCurrLabel", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String incCurrLabel,
        @WebParam(name = "OutSum", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String outSum,
        @WebParam(name = "Language", targetNamespace = "http://merchant.roboxchange.com/WebService/")
        java.lang.String language
    );
}
